/**
 * withCertificatePinning.js
 *
 * Expo config plugin — injects certificate pinning configuration for both
 * Android (network_security_config.xml via OkHttp) and iOS (TSKConfiguration
 * via TrustKit in Info.plist).
 *
 * ─── BEFORE YOUR FIRST PRODUCTION BUILD ────────────────────────────────────
 *
 * 1. Replace PINNED_DOMAIN with your actual API hostname.
 * 2. Replace PRIMARY_HASH and BACKUP_HASH with your server's real SHA-256
 *    SPKI hashes (base-64 encoded, WITHOUT the "sha256/" prefix).
 *
 * To extract the hashes from a live server:
 *
 *   openssl s_client -connect api.yourdomain.in:443 \
 *     -servername api.yourdomain.in 2>/dev/null </dev/null | \
 *   openssl x509 -pubkey -noout | \
 *   openssl pkey -pubin -outform DER | \
 *   openssl dgst -sha256 -binary | \
 *   openssl base64
 *
 * Always pin two hashes (current + next rotation) to avoid locking users out
 * during a certificate renewal.
 *
 * ──────────────────────────────────────────────────────────────────────────
 */

const {
  withDangerousMod,
  withAndroidManifest,
  withInfoPlist,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// ─── Configuration ──────────────────────────────────────────────────────────
// REPLACE all three values before the production build.

const PINNED_DOMAIN = 'api.REPLACE_ME.in';               // ← your API hostname

const PRIMARY_HASH  = 'REPLACE_WITH_PRIMARY_SHA256_SPKI_HASH=';   // ← current cert
const BACKUP_HASH   = 'REPLACE_WITH_BACKUP_SHA256_SPKI_HASH=';    // ← next/backup cert

const PIN_EXPIRATION = '2027-12-31';   // refresh yearly; build fails if expired

// ─── Android: network_security_config.xml ───────────────────────────────────
// OkHttp (the HTTP client used by React Native on Android) automatically
// prepends "sha256/" to each <pin> value, so the raw base-64 hash is correct.

const NETWORK_SECURITY_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  NBFC Certificate Pinning — Android Network Security Config
  See: https://developer.android.com/training/articles/security-config
  Generated by plugins/withCertificatePinning.js — DO NOT EDIT MANUALLY.
-->
<network-security-config>
  <!-- Block all cleartext traffic app-wide (mirrors NSAllowsArbitraryLoads=false on iOS) -->
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>

  <!-- Pin the NBFC API domain -->
  <domain-config cleartextTrafficPermitted="false">
    <domain includeSubdomains="true">${PINNED_DOMAIN}</domain>
    <pin-set expiration="${PIN_EXPIRATION}">
      <!-- Primary certificate (current) -->
      <pin digest="SHA-256">${PRIMARY_HASH}</pin>
      <!-- Backup certificate (next rotation) -->
      <pin digest="SHA-256">${BACKUP_HASH}</pin>
    </pin-set>
  </domain-config>
</network-security-config>
`;

/**
 * Step 1 – Write network_security_config.xml into the generated Android project.
 */
function withAndroidNetworkSecurityConfig(config) {
  return withDangerousMod(config, [
    'android',
    async (modConfig) => {
      const xmlDir = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'res', 'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, 'network_security_config.xml'),
        NETWORK_SECURITY_XML,
        'utf8',
      );
      return modConfig;
    },
  ]);
}

/**
 * Step 2 – Point <application> at the XML file via android:networkSecurityConfig.
 */
function withAndroidManifestConfig(config) {
  return withAndroidManifest(config, (modConfig) => {
    const app = modConfig.modResults.manifest.application?.[0];
    if (app) {
      app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    }
    return modConfig;
  });
}

/**
 * Step 3 – iOS TrustKit configuration (TSKConfiguration) in Info.plist.
 *
 * TrustKit reads this dict at app launch and pins connections at the
 * NSURLSession / CFNetwork level — this is defence-in-depth alongside the
 * JS-layer pinning in src/core/api/api.ts.
 *
 * Note: TSKSwizzleNetworkDelegates must be false when using Expo/RN because
 * the JS bridge already owns the network delegate.
 */
function withIosTrustKit(config) {
  return withInfoPlist(config, (modConfig) => {
    modConfig.modResults['TSKConfiguration'] = {
      TSKSwizzleNetworkDelegates: false,
      TSKPinnedDomains: {
        [PINNED_DOMAIN]: {
          TSKIncludeSubdomains: true,
          TSKEnforcePinning: true,
          TSKExpirationDate: PIN_EXPIRATION,
          TSKPublicKeyHashes: [PRIMARY_HASH, BACKUP_HASH],
          // Algorithms present in your certificate chain (RSA-2048 and EC P-256
          // cover the vast majority of modern TLS certificates).
          TSKPublicKeyAlgorithms: ['TSKAlgorithmRsa2048', 'TSKAlgorithmEcDsaSecp256r1'],
        },
      },
    };
    return modConfig;
  });
}

// ─── Compose & export ────────────────────────────────────────────────────────

/**
 * Combined plugin — registers all three modifications in the correct order.
 * Add to app.json:  "plugins": [ "./plugins/withCertificatePinning", ... ]
 */
module.exports = function withCertificatePinning(config) {
  config = withAndroidNetworkSecurityConfig(config);
  config = withAndroidManifestConfig(config);
  config = withIosTrustKit(config);
  return config;
};
